version: "3"
services: 
  user-service:
    build: ./user-service
    ports:
      - "9091:9091"

  order-service:
    build: ./order-service
    ports:
      - "9092:9092"
    depends_on:
      - user-service
